### PR TITLE
update build script

### PR DESCRIPTION
**Pull request by jovial**
Added gradle wrapper and updated the build script for more modern tooling.

### CODE REVIEW

**Comment by jovial** [comment]
I will try and fix travis...

**Comment by yvesf** [comment]
If I'm not wrong then the `gradlew[.bat]` scripts alone are not sufficient but you also need the some jar?

**Comment by jovial** [comment]
I believe they go and download everything in order to make sure everyone is building with the same version of gradle. At least it seems to work that way for me ;-)

**Comment by jovial** [comment]
Turns out you were right about the gradle-wrapper.jar

**Comment by yvesf** [comment]
looks like you pulled some java 8 classes while travis-ci uses java 7.
From my side it's fine to use java 8 on travis but I don't know what to configure exactly in the travis.yml to change that.

**Comment by yvesf** [comment]
great, thanks!

**Comment by jovial** [comment]
No problem, you did the hard work. Thanks for all your work on andiodine by the way :-)

**Pull request merged**
